var categoryData = {
  // companies: [
  //   "STM",
  //   "ASELSAN",
  //   "ROKETSAN",
  //   "BMC",
  //   "TEKNOPARK İSTANBUL",
  //   "METEKSAN",
  //   "HAVELSAN",
  //   "FNSS",
  //   "TEI",
  //   "TUSAS",
  //   "BAYKAR SAVUNMA",
  //   "OTOKAR",
  //   "NUROL MAKİNA",
  //   "TÜRKSAT",
  // ],
  // clustering: [
  //   "SİBER KÜMELENME",
  //   "TSSK",
  //   "SAHA İSTANBUL",
  //   "OSSA",
  //   "Vizyoner Genç",
  //   "SaSaD",
  // ],
  // countries: [
  //   "TÜRKİYE",
  //   "ABD",
  //   "RUSYA",
  //   "ÇİN",
  //   "DİĞER",
  //   "JAPONYA",
  //   "LİBYA",
  //   "İSRAİL",
  //   "ALMANYA",
  //   "HİNDİSTAN",
  //   "KATAR",
  //   "AZERBAYCAN",
  //   "PAKİSTAN",
  //   "MISIR",
  //   "İRAN",
  //   "SUUDİ ARABİSTAN",
  //   "UKRAYNA",
  //   "İNGİLTERE",
  //   "YUNANİSTAN",
  //   "Güney Kore",
  //   "FRANSA",
  //   "İSPANYA",
  //   "MALEZYA",
  // ],
  // thinkTank: [
  //   "SETA",
  //   "ASSAM",
  //   "İNSAMER",
  //   "HARP TARİHİ",
  //   "TASAM",
  //   "EDAM",
  //   "ThinkTech",
  //   "SDE",
  //   "ORSAM",
  //   "SİYAH GRİ BEYAZ",
  //   "İRAM",
  // ],
  // sources: [
  //   "DERGİLER",
  //   "KİTAPLAR",
  //   "MAKALELER",
  //   "FİLMLER",
  //   "MEKANLAR",
  //   "TARİHİ MEKANLAR",
  //   "RAPORLAR",
  //   "BELGESELLER",
  //   "ANALIZLER",
  // ],
  // youtubers: [
  //   "AYHAN TARAKÇI",
  //   "TOLGA ÖZBEK",
  //   "KEMAL GÖKSU",
  //   "KIYAM",
  //   "TEKNO SAVUNMA",
  //   "SİYAH GRİ BEYAZ",
  //   "UMUT YILDIZ",
  //   "YUSUF AKBABA",
  // ],
  // institutions: [
  //   "SSB",
  //   "MSB",
  //   "TÜBİTAK",
  //   "MKE",
  //   "EYDEP",
  //   "TSK",
  //   "SANAYİ BAKANLIĞI",
  // ],
  // mainCategories: [
  //   "SAVUNMA SANAYİİ",
  //   "SİBER GÜVENLİK",
  //   "UZAY",
  //   "NÜKLEER",
  //   "YAPAY ZEKA",
  //   "TEKNOLOJİ",
  //   "ÇATIŞMA BÖLGELERİ",
  //   "TARİH",
  //   "FİRMALAR",
  //   "YARIŞMALAR",
  //   "EĞİTİMLER",
  //   "TATBİKATLAR",
  //   "SİVİL HAVACILIK",
  //   "ÜNİVERSİTELER",
  //   "AR-GE",
  //   "Gündem",
  //   "RÖPORTAJLAR",
  // ],
}

export default categoryData
